### ISSUE TITLE
ArgumentError: odd number of arguments for Hash

### ISSUE THREAD

**Issue by rubyconvict** [bananastalktome/memcached_stats#3]
```
$ telnet 0 11211
Trying 0.0.0.0...
Connected to 0.
Escape character is '^]'.
add foo 0 0 5                             
bar
STORED
get foo
VALUE foo 0 5
bar
END
quit
Connection closed by foreign host.

$ gem install memcached_stats
Fetching: memcached_stats-0.0.2.gem (100%)
Successfully installed memcached_stats-0.0.2
1 gem installed
$ irb
require 'memcached_stats'
 => true 
stats = MemcachedStats.new
 => #<MemcachedStats:0x00000001268990 @host="localhost", @port=11211, @slab_keys={}> 
stats.fetch_all_slab_keys
 => true 
 stats.slabs
 => {"1"=>{"number"=>"1", "age"=>"211", "evicted"=>"0", "evicted_nonzero"=>"0", "evicted_time"=>"0", "outofmemory"=>"0", "tailrepairs"=>"0", "reclaimed"=>"0", "expired_unfetched"=>"0", "evicted_unfetched"=>"0"}} 

stats.fetch_stats
ArgumentError: odd number of arguments for Hash
	from /home/me/.rvm/gems/ruby-2.2.4/gems/memcached_stats-0.0.2/lib/memcached_stats/base.rb:78:in `[]'
	from /home/me/.rvm/gems/ruby-2.2.4/gems/memcached_stats-0.0.2/lib/memcached_stats/base.rb:78:in `get_summary'
	from /home/me/.rvm/gems/ruby-2.2.4/gems/memcached_stats-0.0.2/lib/memcached_stats/base.rb:33:in `fetch_stats'
	from (irb):3
	from /home/me/.rvm/rubies/ruby-2.2.4/bin/irb:11:in `<main>'

stats = MemcachedStats.new('localhost', 11211)
 => #<MemcachedStats:0x000000011ac9c0 @host="localhost", @port=11211, @slab_keys={}> 
stats.fetch_stats
ArgumentError: odd number of arguments for Hash
	from /home/me/.rvm/gems/ruby-2.2.4/gems/memcached_stats-0.0.2/lib/memcached_stats/base.rb:78:in `[]'
	from /home/me/.rvm/gems/ruby-2.2.4/gems/memcached_stats-0.0.2/lib/memcached_stats/base.rb:78:in `get_summary'
	from /home/me/.rvm/gems/ruby-2.2.4/gems/memcached_stats-0.0.2/lib/memcached_stats/base.rb:33:in `fetch_stats'
	from (irb):5
	from /home/me/.rvm/rubies/ruby-2.2.4/bin/irb:11:in `<main>'
stats = MemcachedStats.new('127.0.0.1', '11211')
 => #<MemcachedStats:0x000000011740e8 @host="127.0.0.1", @port=11211, @slab_keys={}> 
stats.fetch_stats
ArgumentError: odd number of arguments for Hash
	from /home/me/.rvm/gems/ruby-2.2.4/gems/memcached_stats-0.0.2/lib/memcached_stats/base.rb:78:in `[]'
	from /home/me/.rvm/gems/ruby-2.2.4/gems/memcached_stats-0.0.2/lib/memcached_stats/base.rb:78:in `get_summary'
	from /home/me/.rvm/gems/ruby-2.2.4/gems/memcached_stats-0.0.2/lib/memcached_stats/base.rb:33:in `fetch_stats'
	from (irb):7
	from /home/me/.rvm/rubies/ruby-2.2.4/bin/irb:11:in `<main>'
```

**Comment by bananastalktome** [comment]
Thanks for reporting this issue. I was unable to replicate the bug in my environment (tried with Ruby 2.2.4, 2.2.5, 2.3.1 and with memcached 1.4.22 on OSX). So I can try to replicate the issue, can you give me a bit more info about your environment?

It looks like the issue is from line 78 of `./lib/memcached_stats/base.rb`. Can you please run `MemcachedStats.service_connection("stats", 'localhost', 11211).sub("END\r\n","").each_line.inject([]){|arr, line| arr.push(line.sub("STAT ", "").split(' '))}.flatten` and let me know what the output is (if you need to truncate or anonymize it, please also include the length of the array).

**Comment by rubyconvict** [comment]
Here you are:
```
> MemcachedStats.service_connection("stats", 'localhost', 11211).sub("END\r\n","").each_line.inject([]){|arr, line| arr.push(line.sub("STAT ", "").split(' '))}.flatten
 => ["pid", "1536", "uptime", "3336", "time", "1467007105", "version", "1.4.14", "(Ubuntu)", "libevent", "2.0.21-stable", "pointer_size", "64", "rusage_user", "0.055347", "rusage_system", "0.036898", "curr_connections", "5", "total_connections", "6", "connection_structures", "6", "reserved_fds", "20", "cmd_get", "0", "cmd_set", "0", "cmd_flush", "0", "cmd_touch", "0", "get_hits", "0", "get_misses", "0", "delete_misses", "0", "delete_hits", "0", "incr_misses", "0", "incr_hits", "0", "decr_misses", "0", "decr_hits", "0", "cas_misses", "0", "cas_hits", "0", "cas_badval", "0", "touch_hits", "0", "touch_misses", "0", "auth_cmds", "0", "auth_errors", "0", "bytes_read", "7", "bytes_written", "0", "limit_maxbytes", "67108864", "accepting_conns", "1", "listen_disabled_num", "0", "threads", "4", "conn_yields", "0", "hash_power_level", "16", "hash_bytes", "524288", "hash_is_expanding", "0", "expired_unfetched", "0", "evicted_unfetched", "0", "bytes", "0", "curr_items", "0", "total_items", "0", "evictions", "0", "reclaimed", "0"]
```

```
$ sudo aptitude show memcached
Pakiet: memcached                                 
Stan: zainstalowany
Zainstalowany automatycznie: nie
Wersja: 1.4.14-0ubuntu9
Priorytet: opcjonalny
Sekcja: web
Opiekun: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architektura: amd64
Rozmiar rozpakowanego: 229 k
Wymaga: libc6 (>= 2.17), libevent-2.0-5 (>= 2.0.10-stable), libsasl2-2 (>= 2.1.24), perl, lsb-base (>= 3.2-13), adduser
Sugeruje: libcache-memcached-perl, libmemcached
W konflikcie z: memcached
Opis: [OMITTED]
```

**Comment by bananastalktome** [comment]
I pushed a new version (0.0.4) which should fix this issue. Please let me know if it works.

The problem was that I was splitting each line of the result of `stats` on blank spaces, and though each key/value pair I have seen has always had the "value" as a single item without a space in it, but ubuntu shows the version as `version 1.4.14 Ubuntu` (with an extra space there).

**Comment by rubyconvict** [comment]
It works now, thank you.
